name = "neko-auth"
main = "build/index.js"
compatibility_date = "2026-04-06"

[build]
command = "worker-build --release"

[durable_objects]
bindings = [
  { name = "OIDC_STATE_OBJECT", class_name = "OidcStateObject" },
  { name = "USER_SESSION_OBJECT", class_name = "UserSessionObject" },
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["OidcStateObject", "UserSessionObject"]

[env.dev]
