name = "neko-auth"
main = "build/index.js"
compatibility_date = "2026-04-06"

[build]
command = "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y && export PATH=\"$HOME/.cargo/bin:$PATH\" && cargo install -q worker-build && worker-build --release"